### ISSUE TITLE
[BUG] SxB Customizer does not work properly via Stardust Core Lite (QuickBar) 

### ISSUE THREAD

**Issue by xBATSYx** [ErinaSugino/Starbound-SBR-Mod#14]
The SxB Customizer Item itself works and you can change sub-genders, etc. But if you enter the same customizer through [Stardust Core Lite](https://steamcommunity.com/sharedfiles/filedetails/?id=2512589532), and there is no way to change anything other than None.
PS. Thanks for bringing the mod to life.😘

**Comment by ErinaSugino** [comment]
That the customizer UI does not work with QuickbarMini (and hance probably its successor Stardust Core Lite  too) is a known bug from the original mod, due to the way how QM just opens the the UI via config whereas SxB does fetch and pre-append the actual statistics to the loaded config prior to opening the ScriptPane.

This will be fixed in a future update, but hasn't been deemed high priority for now.
