### ISSUE TITLE
UI not functioning correctly.

### ISSUE THREAD

**Issue by Jyroscopic360** [ErinaSugino/Starbound-SBR-Mod#15]
When interacting with a sex node the UI is either non-existant or low transparency with no positions showing. The transparency does not change when hovering over it with the cursor and clicking the UI produces no results. This was tested using the mod by itself and with its known compatible mods up to date with no other mods intruding and a fresh character and universe.

**Comment by ErinaSugino** [comment]
That the UI breaks (never fully loads, stays transparent, doesn't react to anything) is only caused by other mods reverting scripts, i.e. primarily those that modify the POV module as that has drastically changed. So this should not be possible with the mod itself, and when you speak about "only using compatible mods" that probably includes "POV Redux" and "Teratophilia Scenes", both of which need a specific version to be compatible.

For POV Redux you need Version 4.2.0 or newer, for Terato Scenes you need the newest uploaded file called "SxB - TemTem TeratoScenes". Otherwise it's an old incompatible version causing exactly this bug.

For any further help, please follow standard bug reporting procedures and provide a log file.

**Comment by Jyroscopic360** [comment]
Ahh Terato Scenes was it. Didn't know the "SxB - TemTem TeratoScenes" file was the same thing just updated for your mod. I'm sorry for bothering you.
