### ISSUE TITLE
[BUG] StarExtensions climax crash

### ISSUE THREAD

**Issue by Dgarden7** [ErinaSugino/Starbound-SBR-Mod#54]
I started playing Starbound with mods, one of them was StarExtensions, everything was going well, until when the time came to do X things, just when the characters are at the climax, the game closes... I was searching and I saw that the culprit was StarExtensions so I removed it. But something strange happened, and now I felt that the characters were too static and didn't look very alive... It turns out that one of the additions of StarExtensions were the idle animations and the rotation of the head in the direction of the cursor, so this is specific function of StarExtensions is incompatible with Sexbound for any reason...

So my proposal is, would it be possible to make that function compatible? It really is very annoying for me to play without the StarExtension animations... I have faith that something can be done about it, and I leave this proposal open, since I believe that both mods make the characters more alive!

I leave here the specific StarExtension function I am referring to:
 
![Action 11-10-2023 21-00-06](https://github.com/ErinaSugino/Starbound-SBR-Mod/assets/70489754/a9db7b5c-ba46-450a-bab1-e0fe179429de)

Thanks for your attention <3

**Comment by ErinaSugino** [comment]
StarExtension itself has nothing* that should interfere with any other mod. So "compatibility" is already given.

\* nothing, bar one fix to the game's spaghetti source code, which actually caused something like you described to happen upon climax, because in original Sexbound Locuturus was a bit lazy (or something) and coded a feature that required the Starbound source code to be broken, resulting in the bug only occuring when StarExtension fixed it.

The error you described has already been brought up in the past - and should also have been fixed in the past. You are saying the game closes upon climax... Let me guess. You were on your ship when that happened? And if you were to look into `starbound.log` file, the last thing the game record is a WorldInstance Crash where the traceback says something about "Proctiles"? If yes, this should have been fixed. If not, this is something new.

Either way, I will need the logfile of that session.

**Comment by Dgarden7** [comment]
That's right, it really happens anywhere, if sex happens on a planet, when it's about to climax it sends me into space and I fall into the void, and if it happens inside the ship, the game just kicks me out to the main menu wit this screen... 

![image](https://github.com/ErinaSugino/Starbound-SBR-Mod/assets/70489754/db0fcd1c-a7d5-4d83-8b4a-63fa3177b68b)

Here is the log: 

[Log and video.zip](https://github.com/ErinaSugino/Starbound-SBR-Mod/files/12874425/Log.and.video.zip)

**Comment by Dgarden7** [comment]
That's right, it really happens anywhere, if sex happens on a planet, when it's about to climax it sends me into space and I fall into the void, and if it happens inside the ship, the game just kicks me out to the main menu wit this screen... 

![image](https://github.com/ErinaSugino/Starbound-SBR-Mod/assets/70489754/db0fcd1c-a7d5-4d83-8b4a-63fa3177b68b)

Here is the log: 

[Log and video.zip](https://github.com/ErinaSugino/Starbound-SBR-Mod/files/12874425/Log.and.video.zip)

**Comment by ErinaSugino** [comment]
Just to be sure I need you to do some testing for me.
Does this bug also occur when you use a clean install of *only* Sexbound Reborn?

Since temporarily removing all other mods will leave you with no options to control NPCs into sexnodes for easy testing, you can use `/admin` in chat to give yourself admin privileges (Singleplayer only of course) and then hover your mouse over an NPC and type `/entityeval status.setResource('arousal', 100)` to force them into a sexnode, just like Aphrodite's Bow's secondary attack would do. Does the error still occur under these circumstances?

Keep in mind to **backup your storage folder and use a fresh character to test this**, as removing mods on a running savefile might cause even more problems.

**Comment by Dgarden7** [comment]
Okay, I'm going to do those things, it will take me a little time, as soon as I have the results I'll let you know.

**Comment by Dgarden7** [comment]
When I try to do the command it tells me “Nil” and nothing happens
![image](https://github.com/ErinaSugino/Starbound-SBR-Mod/assets/70489754/d134182c-5f74-4d66-9525-5fa63f4454f5)

**Comment by ErinaSugino** [comment]
The result "nil" means no error, as this command does not return anything - just sets a value. That nothing is happening is probably due to the fact that there is no sexnode around. You most likely have to clear (or skip upon character creation) the tutorial, then get an NPC and a sexnode - wooden table is probably the easiest.

Anyway, I just remembered something. When have you downloaded the Lustbound SBR patch?

**Comment by Dgarden7** [comment]
Ok, I have done it and the game has not crashed, it is a clean installation with Sexbound reborn and StarExtension

**Comment by ErinaSugino** [comment]
So, yeah. When have you switched to/started using SBR and have you ever re-downloaded the patches for Lustbound and Aphrodite's Bow again after that?

**Comment by Dgarden7** [comment]
Yes, I did, initially I played with the old SexBound, and this same error happened, then I installed SexBound Reborn and the 2 patches for the 2 compatible mods and the problem kept happening exactly the same in both, my game and starting a new one

**Comment by ErinaSugino** [comment]
But what version? SBR 1.0 Revision 1 Hotfix 1 is the version in which this specific error was fixed. The source of the error, climax projectiles, are also affected by Lustbound however. So the fix also applies to the Lustbound SBR Patch. Meaning if you don't have the newest version of the Lustbound patch downloaded, the one delivered with the R1H1 release, that's the source of the error. Also the reason why it now works when you only run clean SBR.

**Comment by Dgarden7** [comment]
I make sure that I install everything in its latest version, when I add the other mods again the game breaks again at the climax, I have the screenshot of the mods here: 

![Desktop 12-10-2023 0-18-11-451](https://github.com/ErinaSugino/Starbound-SBR-Mod/assets/70489754/728a24f0-0943-4c8c-a52b-e8645eaebbac)

**Comment by ErinaSugino** [comment]
Yeah, I'm afraid just adding all mods back won't help solving this. You'd need to do it one mod at a time, and test inbetween every single one to find out exactly which one causes it (of course, Lustbound or Aphrodite's Bow and their respective patches need to stay together.)

**Comment by Dgarden7** [comment]
Okay, I'll do it, I'll see if I find the exact cause, I'll report back if I find anything! Thanks

**Comment by Dgarden7** [comment]
Okay i found the! Pheromones mod 

https://www.loverslab.com/files/file/12006-sxb-pheromones-plugin/

When it is about to reach the climax, the mod activates and releases the pheromones, that is apparently what causes the game to break

**Comment by ErinaSugino** [comment]
Ah yes. That mod doesn't do alot, but it copied the mistake from original Sexbound. You should bring the bug up with them, though I have no idea if anyone even still checks the mod. Never used it myself, never hear much about it.

I'll close this issue as invalid then, now.
