### ISSUE TITLE
Sexbound Reborn "Update/TriggerUpdate" Bug.

### ISSUE THREAD

**Issue by SomeBugReporter** [ErinaSugino/Starbound-SBR-Mod#6]
[11:41:16.489] [Error] Exception while invoking lua function 'update'. (LuaException) Error code 2, [string "/interface/sexbound/sexui.lua"]:222: attempt to call a nil value (method 'triggerUpdate')
stack traceback:
	[C]: in method 'triggerUpdate'
	[string "/interface/sexbound/sexui.lua"]:222: in field 'onSuccess'
	[string "/scripts/messageutil.lua"]:44: in method 'update'
	[string "/interface/sexbound/sexui.lua"]:118: in method 'update'
	[string "/interface/sexbound/sexui.lua"]:278: in function <[string "/interface/sexbound/sexui.lua"]:277>
[starbound (2).log](https://github.com/ErinaSugino/Starbound-SBR-Mod/files/10904488/starbound.2.log)

Line 1799 and below line 1799.

Server Log not inserted as I am a singleplayer person, And don't have any servers I play on.

Tis as simple as trying to enter a sexnode to recreate it, I also have a crapton of mods that could be conflicting, (I'm looking at you FR.) So do notify of any conflicting mods.

Also this Error Line came out with and without the OG Sexbound API File.
I used source files for both SXB and SXBR.

**Comment by ErinaSugino** [comment]
> Also this Error Line came out with and without the OG Sexbound API File.

Sexbound Reborn is Sexbound, so you should never use both versions combined. Theoretically SBR should just override SxB because it loads later, but better not try it.

> Tis as simple as trying to enter a sexnode to recreate it, I also have a crapton of mods that could be conflicting

That will certainly be it. Sexbound Reborn, by default, is to be considered incompatible with every mod from the old SxB unless proven otherwise or fixed. Your error message says that the method "triggerUpdate" isn't there, which means the new altered UI/POV code of Reborn was partially changed back by another mod that patched it. In the current state (updates for SBR compat still pending but technically done) this could very well just be "POV Redux".
